version: '3.8'

services:
  tablet-monitoring-api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: jd-tablet-monitoring-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - API_HOST=0.0.0.0
    volumes:
      - ./static:/app/static:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 