version: '3.8'

services:
  jd-tablet-monitoring-api:
    image: python:3.11-slim
    container_name: jd-tablet-monitoring-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=${DATABASE_URL:-}
    working_dir: /app
    command: >
      sh -c "
      apt-get update && apt-get install -y curl git gcc g++ libpq-dev &&
      git clone https://github.com/Laika-Dynamics-Ltd/jd-engineering-monitoring-api.git . &&
      pip install --no-cache-dir -r requirements.txt &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --log-level info
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    volumes:
      - ./static:/app/static 